#!/bin/bash
DIR=$(cd $(dirname "$0"); pwd)
cd $DIR
echo "----------------------------------------------------------"
echo " Champ's RLE to PNG conversion script (Android bootsplash)"
echo "----------------------------------------------------------"
echo " ImageMagick is required. Make sure it is present "
echo
echo "make sure you have placed 'bootsplash.rle' file in input folder"
echo
echo "or"
echo
echo "you have called the png file in argument"

read -p "Press [Enter] key to continue"

rm -f logo*
if [ ! $1  ]
	then
		cp -f ../input/bootsplash.rle ./logo.rle
	else
		cp -f $1 ./logo.rle
fi

if [ ! -e logo.rle ]
then
	echo "RLE logo file not found"
	exit
fi

ARCH=$(uname -s).$(uname -m)

if [ ! -e ./5652rgb.$ARCH ]
	then
		echo " Precompiled binary not found for your architecture"
		echo " I will compile it for you now"
		echo " Please ensure latest gcc is installed"
		read -p "Press [Enter] key to continue"
		gcc -O2 -Wall -Wno-unused-parameter -o 5652rgb.$ARCH from565.c
fi

echo "I cannot detect image size from rle files :( "
echo "please type size of the bootlogo [eg. 480x854] and press enter to continue"
read IMG_SIZE
./5652rgb.$ARCH -rle < logo.rle > logo.raw
convert -depth 8 -size $IMG_SIZE rgb:logo.raw logo.png

cp -f logo.png ../output/bootsplash.png
echo "----------------------------"
echo " Please find converted file bootsplash.png inside output folder"

rm -f logo.png logo.rle logo.raw
