#!/bin/bash
DIR=$(cd $(dirname "$0"); pwd)
cd $DIR
echo " --------------------------------------------------------"
echo "   Champ's Script to extract zImage and ramdisk from ftf "
echo "        using DoomLord's Kernel.sin unpacker perl script "
echo " --------------------------------------------------------"

echo " PLease note that " 
echo " If there are more than one ftf files, then only first file will be acted upon"
echo " Other ftf files will be ignored"
read -p "Press [Enter] to continue"
if [  $1 ]
then
	cp $1 kernel.ftf
else
	if [ -e ../../input/kernel.ftf ]
	then
		cp ../../input/kernel.ftf kernel.ftf
	else
		echo "Please place kernel.ftf file in input folder"
		exit
	fi
fi


if [ -e kernel.ftf ]
then
	rm -f temp.ftf
	cp *.ftf temp.ftf
	jar xvf temp.ftf kernel.sin
	rm -f temp.ftf
	./unpack-kernelsin.pl kernel.sin
else
	echo "No ftf found"
	exit
fi
rm -r -f kernel-contents
mkdir -p kernel-contents
rm -f *.ftf
mv kernel.sin* kernel-contents/.
cd kernel-contents
mv *.cpio.gz ramdisk.cpio.gz
mv  *kernel zImage
mv *header header-file
mv kernel.sin-ramdisk ramdisk
cd ..
echo "------------------------------------------------------"
echo "find your files inside kernel-contents folder"
echo "ramdisk has been extracted to ramdisk folder"
echo "------------------------------------------------------"
echo "----Thank you---"

