#!/bin/bash
DIR=$(cd $(dirname "$0"); pwd)
cd $DIR
echo "---------------------------------------------------------"
echo "-----------Extract Ramdisk (Android )-------------------"
echo "Please make sure that "
echo "ramdisk is named 'ramdisk.cpio.gz' or 'ramdisk.img'"
echo "and kept in input folder"
echo
echo "or"
echo
echo "you have called ramdisk file in arguement"

if [ ! $1 ]
then
	if [  -e ../input/ramdisk.img  -a  -e ../input/ramdisk.cpio.gz   ]
	then
	
		echo "Please use either ramdisk.img or ramdisk.cpio.gz "
		echo "I cannot extract more than one ramdisk together"
		echo "There should be only one ramdisk"
		exit
	fi

	if [ -e ../input/ramdisk.img ]
	then
		cp -f ../input/ramdisk.img ./ramdisk
	fi

	if [ -e ../input/ramdisk.cpio.gz ]
	then 
		cp -f ../input/ramdisk.cpio.gz ./ramdisk
	fi

else
	cp -f $1 ./ramdisk
fi

if [ -e ramdisk ]
then
	rm -f -r ramdisk-contents
	mkdir -p ramdisk-contents
	cd ramdisk-contents
	gzip -dc ../ramdisk | cpio -i
	cd ..
	rm -f -r ../output/ramdisk-contents
	mv -f ramdisk-contents ../output
	rm -f ramdisk
	echo "ramdisk extracted ramdisk-contents inside output directory"
	echo "----------thank you !!! -----------"

else
	echo "------ERROR-------"
	echo "Ramdisk not found!!"
	echo " ----I'm Sorry!! ------"
	exit
	
fi
