#!/bin/bash
echo "---------------------------------------------------------"
echo "-----------Extract Ramdisk (Android )-------------------"
echo "ramdisk should be named 'initrd.img' or 'ramdisk.cpio.gz'"



if [  -e initrd.img  -a  -e ramdisk.cpio.gz   ]
then
	
	echo "Please use either initrd.img or ramdisk.cpio.gz "
	echo "I cannot extract more than one ramdisk together"
	echo "There should be only one ramdisk"
	exit
fi

if [ -e initrd.img ]
then
	mv -f initrd.img ramdisk
fi

if [ -e ramdisk.cpio.gz ]
then 
	mv -f ramdisk.cpio.gz ramdisk
fi

if [ -e ramdisk ]
then
	rm -f -r ramdisk-contents
	mkdir -p ramdisk-contents
	cd ramdisk-contents
	gunzip -c ../ramdisk | cpio -i
	echo "ramdisk extracted to folder ramdisk-contents"
	echo "----------thank you !!! -----------"

else
	echo "Ramdisk not found!!"
	echo " ----I'm Sorry!! ------"
	
fi