#!/bin/bash
echo "----------------------------------------------------------------"
echo "We can build kernels for the following devices "
echo "----------------------------------------------------------------"
echo
echo "1. Xperia S (gingerbread 2.3.x)"
echo "2. Xperia S (ice cream sandwich 4.0.x)"
echo "3. Xperia P (gingerbread 2.3.x)"
echo
echo "----------------------------------------------------------------"
echo
echo "Please enter the desired choice and press enter"
read ELFOPT
case $ELFOPT in
	1) ./mk/S-gb ;;
	2) ./mk/S-ics ;;
	3) ./mk/P-gb ;;
esac
clear
