#!/bin/bash

echo " --------------------------------------------------------"
echo "   Champ's Script to extract zImage and ramdisk from ftf "
echo "        using DoomLord's Kernel.sin unpacker perl script "
echo " --------------------------------------------------------"

echo " PLease note that " 
echo " If there are more than one ftf files, then only first file will be acted upon"
echo " Other ftf files will be ignored"
read -p "Press [Enter] to continue"


if  [ -e kernel.ftf ]
then
	echo "----ERROR---"
	echo "please rename your ftf to something other than kernel.ftf"
	echo "there should be not file called kernel.ftf in this folder"
	echo "----Thank you---"
	exit
fi

cp *.ftf kernel.ftf
jar xvf kernel.ftf kernel.sin
rm -f kernel.ftf
./unpack-kernelsin.pl kernel.sin
rm -r -f kernel-contents
mkdir -p kernel-contents
mv kernel.sin* kernel-contents/.
cd kernel-contents
mv *.cpio.gz ramdisk.cpio.gz
mv  *kernel zImage
mv *header header-file
mv kernel.sin-ramdisk ramdisk
cd ..
echo "------------------------------------------------------"
echo "find your files inside kernel-contents folder"
echo "ramdisk has been extracted to ramdisk folder"
echo "------------------------------------------------------"
echo "----Thank you---"

