#!/bin/bash
DIR=$(cd $(dirname "$0"); pwd)
cd $DIR
echo " --------------------------------------------------------"
echo "   Champ's Script to extract zImage and ramdisk from ftf "
echo "        using DoomLord's Kernel.sin unpacker perl script "
echo " --------------------------------------------------------"

read -p "Press [Enter] to continue"
rm -f ./kernel.ftf
if [  $1 ]
then
	cp $1 ./kernel.ftf
else
	if [ -e ../../input/kernel.ftf ]
	then
		cp ../../input/kernel.ftf ./kernel.ftf
	else
		echo "Please place kernel.ftf file in input folder"
		exit
	fi
fi


if [ -e kernel.ftf ]
then
	if [ $(command -v jar) ]
	then
		jar xvf kernel.ftf kernel.sin
	else
		echo "--------------ERROR-------------------------"
		echo " 'jar' program not installed in your system "
		echo " install 'java' or 'fastjar' or open-jdk or sun-java-jdk "
		jar 		
		rm -f kernel.ftf
		exit
	fi 
	rm -f kernel.ftf
	./unpack-kernelsin.pl kernel.sin
else
	echo "No ftf found"
	rm kernel.ftf
	exit
fi

rm -r -f kernel-contents
mkdir -p kernel-contents
rm -f *.ftf
mv kernel.sin* kernel-contents/.
cd kernel-contents
mv *.cpio.gz ramdisk.cpio.gz
mv  *kernel zImage
mv *header header-file
mv kernel.sin-ramdisk ramdisk
cd ..
mv kernel-contents ../../output/
echo "------------------------------------------------------"
echo " please open the output folder"
echo "find your files inside kernel-contents folder"
echo "ramdisk has been extracted to ramdisk sub-folder"
echo "------------------------------------------------------"
echo "----Thank you---"

